# Generated by Django 5.2.16 on 2026-07-29 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certificates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["is_deleted"], name="certificate_is_dele_dfbe53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["certificate_number"], name="certificate_certifi_cd0c46_idx"
            ),
        ),
    ]
