# Generated by Django 5.2.16 on 2026-07-29 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="subjects.categories",
            ),
        ),
    ]
