# Generated by Django 5.2.16 on 2026-07-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_categories_subject_author_subject_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
