# Generated by Django 5.2.16 on 2026-07-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0004_categories_author_categories_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={},
        ),
        migrations.AddField(
            model_name="categories",
            name="author_first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="categories",
            name="author_last_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
