# Generated by Django 5.2.16 on 2026-07-25 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0005_alter_categories_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="subject",
            name="author_first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="subject",
            name="author_last_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterModelTable(
            name="categories",
            table="categories",
        ),
        migrations.AlterModelTable(
            name="subject",
            table="subjects",
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "db_table": "modules",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="subjects.module",
                    ),
                ),
            ],
            options={
                "db_table": "topics",
                "ordering": ["-created_at"],
            },
        ),
    ]
