# Generated by Django 5.2.16 on 2026-07-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Examination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("IELTS", "IELTS"),
                            ("DTM", "DTM"),
                            ("SAT", "SAT"),
                            ("MILLIY", "Milliy Sertifikat"),
                        ],
                        default="DTM",
                        max_length=20,
                    ),
                ),
                (
                    "duration_time",
                    models.PositiveIntegerField(
                        default=120, help_text="Test davomiyligi (daqiqada)"
                    ),
                ),
                ("transition_assessment", models.FloatField(default=56.7)),
                (
                    "instruction_audio",
                    models.FileField(
                        blank=True, null=True, upload_to="exams/instructions/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "examinations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="options/images/"
                    ),
                ),
            ],
            options={
                "db_table": "options",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("middle", "Middle"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        max_length=10,
                    ),
                ),
                (
                    "passage_text",
                    models.TextField(
                        blank=True, help_text="Reading text matni", null=True
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="questions/audio/"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="questions/images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("is_passed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "results",
                "ordering": ["-completed_at"],
            },
        ),
    ]
